# Plugin \Drupal\ckeditor_config\Plugin\CKEditorPlugin\CustomConfig
ckeditor.plugin.customconfig:
  type: mapping
  label: 'CKEditor custom configuration'
  mapping:
    ckeditor_custom_config:
      type: string
      label: 'CKEditor custom config'
