name: 'CKEditor custom config'
type: module
description: 'Extends core CKEditor to support custom configuration.'
package: Custom
# core: 8.x

dependencies:
  - drupal:ckeditor (>=8.5)

# Information added by Drupal.org packaging script on 2019-05-06
version: '8.x-2.0'
core: '8.x'
project: 'ckeditor_config'
datestamp: 1557181384
